name: Build and deploy Python app to Azure Web App - chatbot-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        working-directory: bot
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        working-directory: bot
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      # Optional: Add test step here

      - name: Zip artifact for deployment
        working-directory: bot
        run: zip -r ../release.zip . -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D8D5B3B32BBB4C989BC98D25502E65F6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D67754F47FDC4B5D86CC447246171316 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1A027A3DE3CF41FAA42C5E05CB9BAB7A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'chatbot-1'
          package: .
          
